# -*- coding: utf-8 -*-
"""Data Extractor

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18swvcBB6dQ22hLVxp-8BeJN0M7dgdWy-
"""

from google.colab import drive
drive.mount('/content/drive')

import csv

input_path = "/content/drive/Shareddrives/1:1 Advaith Menon/Downloads/nihcc/DL_info.csv"
image_directory = "/content/drive/Shareddrives/1:1 Advaith Menon/Downloads/nihcc/Images_png/"
output_path = "/content/drive/Shareddrives/1:1 Advaith Menon/Downloads/processed-nihcc/"

import shutil
import pandas as pd

correct = pd.read_csv(input_path)

for i, r in correct.iterrows():


  fileName = r[0]
  inputName = image_directory + fileName[:12] + "/" + fileName[13:]
  typeLesion = r[9]
  outputDirectory = output_path + str(typeLesion) + "/" + fileName

  if typeLesion <0:
    continue

  print(typeLesion, fileName, inputName, outputDirectory)
  shutil.copy(inputName, outputDirectory)