# -*- coding: utf-8 -*-
"""DataAugmentationGenerator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fOo_EMDq17HTXVozBUEt44m8kQ7GLXfp
"""

from google.colab import drive
drive.mount('/content/drive')

in_path = "/content/drive/Shareddrives/1:1 Advaith Menon/Downloads/final_datasets/Vanilla_Dataset/8/"
out_path = "/content/drive/Shareddrives/1:1 Advaith Menon/Downloads/final_datasets/600_Total_DA/8/"

from keras.applications.resnet import preprocess_input
from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rotation_range = 30, horizontal_flip=True)

BATCH_SIZE = 16

IMG_SIZE = (224, 224)

train_generator = train_datagen.flow_from_directory(in_path,
                                                target_size=IMG_SIZE,
                                                color_mode='rgb',
                                                batch_size=BATCH_SIZE,
                                                class_mode='categorical',
                                                shuffle=True)

import cv2
import shutil
from google.colab.patches import cv2_imshow

x=-1
for image_set in train_generator:
    if(x>74):
        break
    for image in image_set[0]:
        if(x>74):
          break
        else:
          x+=1
          print("Image " + str(x))
          cv2.imwrite("/content/augmented_image_" + str(x) + ".png", image)
          shutil.copy("/content/augmented_image_" + str(x) + ".png", out_path)