# -*- coding: utf-8 -*-
"""Lesion Image Enhancer

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QOdP-zm2mIT8EGcH9aC-LhS5eMIKQqCI
"""

import cv2
from google.colab.patches import cv2_imshow
import numpy as np
import os
from google.colab import drive
import shutil
drive.mount('/content/drive')

p=1
while p<9:
  in_path = "/content/drive/Shareddrives/1:1 Advaith Menon/Downloads/processed-nihcc/OriginalImages/" + str(p) + "/"
  out_path = "/content/drive/Shareddrives/1:1 Advaith Menon/Downloads/final_datasets/Vanilla_Dataset/" + str(p) + "/"
  for filename in os.listdir(in_path):
    print(filename[:len(filename)-4])
    image = cv2.imread(in_path+filename)
    new_image = np.zeros(image.shape, image.dtype)
    contrast = 15.0
    for y in range(image.shape[0]):
      for x in range(image.shape[1]):
         for c in range(image.shape[2]):
            new_image[y,x,c] = contrast*image[y,x,c]

    cv2.imwrite(filename[:len(filename)-4] + "_updated.png", new_image)
    shutil.copy(filename[:len(filename)-4] + "_updated.png", out_path)
  p+=1

image = cv2.imread("000010_02_02_100.png")

new_image = np.zeros(image.shape, image.dtype)
contrast = 1.0
brightness = 0


for y in range(image.shape[0]):
    for x in range(image.shape[1]):
        for c in range(image.shape[2]):
            new_image[y,x,c] = 15*image[y,x,c]
cv2_imshow(image)
cv2_imshow(new_image)
cv2.waitKey()