# -*- coding: utf-8 -*-
"""MS-SSIM

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10ZAlr33bETvzPYQKzj8m1cgxikcJL3MP
"""

from google.colab import drive
drive.mount('/content/drive')
from google.colab import files

pip install pytorch-msssim

from pytorch_msssim import ssim, ms_ssim, SSIM, MS_SSIM
import pathlib
X = list(pathlib.Path("/content/drive/Shareddrives/1:1 Advaith Menon/Downloads/final_datasets/Vanilla_Dataset/").rglob('*/*.png'))
Y = list(pathlib.Path("/content/drive/Shareddrives/1:1 Advaith Menon/Downloads/final_datasets/GAN_Dataset/").rglob('*/**/*.png'))
countX = len(list(X))
countY = len(list(Y))
print(countX)
print(countY)

for image1 in X:
  for image2 in Y:
    print('x')

    ssim_val = ssim( image1, image2, data_range=255, size_average=False)
    ms_ssim_val = ms_ssim( image1, image2, data_range=255, size_average=False )

    ssim_loss = 1 - ssim( image1, image2, data_range=255, size_average=True)
    ms_ssim_loss = 1 - ms_ssim( image1, image2, data_range=255, size_average=True )
    ssim_module = SSIM(data_range=255, size_average=True, channel=3) # channel=1 for grayscale images
    ms_ssim_module = MS_SSIM(data_range=255, size_average=True, channel=3)
    ssim_loss = 1 - ssim_module(image1, image2)
    ms_ssim_loss = 1 - ms_ssim_module(image1, image2)

print(ssim_val)
print(ms_ssim_val)